---
services:
  db:
    image: postgres:14-alpine
    ports:
      - "${DB_PORT}:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - db:/var/lib/postgresql/data
  web:
    tty: true
    stdin_open: true
    build:
      context: .
      network: host
    command: sh -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/opt/app
    networks:
      - default
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      RAILS_LOG_TO_STDOUT: 'yes'
      PAGER: 'less'

volumes:
  db:
