---
services:
  postgres_db:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - db:/var/lib/postgresql/data
  web:
    tty: true
    stdin_open: true
    build:
      context: .
    command: sh -c "rm -f tmp/pids/server.pid && /bin/bash"
    volumes:
      - .:/app
      - ../arfi:/arfi
    networks:
      - default
    ports:
      - "3000:3000"
    environment:
      RAILS_LOG_TO_STDOUT: 'yes'
      PAGER: 'less'
      PG_DB_HOST: postgres_db
      PG_DB_PORT: 5432
      PD_DB_USERNAME: postgres
      PG_DB_PASSWORD: postgres

volumes:
  db:
