# PostgreSQL. Versions 9.3 and up are supported.
#
# Install the pg driver:
#   gem install pg
# On macOS with Homebrew:
#   gem install pg -- --with-pg-config=/usr/local/bin/pg_config
# On Windows:
#   gem install pg
#       Choose the win32 build.
#       Install PostgreSQL and put its /bin directory on your path.
#
# Configure Using Gemfile
# gem "pg"
#
default: &default
  pg_db: &pg
    adapter: postgresql
    encoding: unicode
    username: <%= ENV.fetch('PD_DB_USERNAME', 'postgres') %>
    password: <%= ENV.fetch('PG_DB_PASSWORD', 'postgres') %>
    host: <%= ENV.fetch('PG_DB_HOST', 'localhost') %>
    port: <%= ENV.fetch('PG_DB_PORT', '5432') %>
    prepared_statements: false
    # For details on connection pooling, see Rails configuration guide
    # https://guides.rubyonrails.org/configuring.html#database-pooling
    pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  mysql_db: &mysql
    adapter: mysql2
    encoding: utf8mb4
    username: <%= ENV.fetch('MYSQL_DB_USERNAME', 'root') %>
    password: <%= ENV.fetch('MYSQL_DB_PASSWORD', 'mysql') %>
    host: <%= ENV.fetch('MYSQL_DB_HOST', '127.0.0.1') %>
    port: <%= ENV.fetch('MYSQL_DB_PORT', '3306') %>
    migrations_paths: db/mysql_db_migrate
    flags:
      - -COMPRESS
      - FOUND_ROWS
      - MULTI_STATEMENTS
    secure_auth: false
    pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  pg_db:
    <<: *pg
    database: pg_poc_arfi_72_development
  mysql_db:
    <<: *mysql
    database: my_poc_arfi_72_development

  # The specified database role being used to connect to PostgreSQL.
  # To create additional roles in PostgreSQL see `$ createuser --help`.
  # When left blank, PostgreSQL will use the default role. This is
  # the same name as the operating system user running Rails.
  #username: poc_arfi_72

  # The password associated with the PostgreSQL role (username).
  #password:

  # Connect on a TCP socket. Omitted by default since the client uses a
  # domain socket that doesn't need configuration. Windows does not have
  # domain sockets, so uncomment these lines.
  #host: localhost

  # The TCP port the server listens on. Defaults to 5432.
  # If your server runs on a different port number, change accordingly.
  #port: 5432

  # Schema search path. The server defaults to $user,public
  #schema_search_path: myapp,sharedapp,public

  # Minimum log levels, in increasing order:
  #   debug5, debug4, debug3, debug2, debug1,
  #   log, notice, warning, error, fatal, and panic
  # Defaults to warning.
  #min_messages: notice

# Warning: The database defined as "test" will be erased and
# re-generated from your development database when you run "rake".
# Do not set this db to the same as development or production.
test:
  <<: *default
  pg_db:
    <<: *pg
    database: pg_poc_arfi_72_test
  mysql_db:
    <<: *mysql
    database: my_poc_arfi_72_test

# As with config/credentials.yml, you never want to store sensitive information,
# like your database password, in your source code. If your source code is
# ever seen by anyone, they now have access to your database.
#
# Instead, provide the password or a full connection URL as an environment
# variable when you boot the app. For example:
#
#   DATABASE_URL="postgres://myuser:mypass@localhost/somedatabase"
#
# If the connection URL is provided in the special DATABASE_URL environment
# variable, Rails will automatically merge its configuration values on top of
# the values provided in this file. Alternatively, you can specify a connection
# URL environment variable explicitly:
#
#   production:
#     url: <%= ENV["MY_APP_DATABASE_URL"] %>
#
# Read https://guides.rubyonrails.org/configuring.html#configuring-a-database
# for a full overview on how database connection configuration can be specified.
#
production:
  <<: *default
  database: poc_arfi_72_production
  username: poc_arfi_72
  password: <%= ENV["POC_ARFI_72_DATABASE_PASSWORD"] %>
